### PR TITLE
Fix build and assembly

### PR DESCRIPTION
**Pull request by homosepian**
- Upgraded to latest weka version, added weka's liblinear library and wrapper because the old version conflicts with dkpro (license is GNU General Public License 3 so should be fine to redistribute). All tests pass, including previously failed NemexWekaClassificationEDATest.
- Added a module for creating the distribution zip file as required in maven-assembly-plugin 3.0.0. Use `mvn -P release clean package` to build distribution zip file.

NOTE:
The Jenkins build seems to be calling `mvn assembly:assembly`, which doesn't exit any more. Instead the build should call `mvn clean package` and the assembly will be triggered automatically when the new "distribution" module is built.
The zip file is created as <eop-base-dir>/distribution/target/distribution-1.2.4-SNAPSHOT-bin.zip.
Assuming Jenkins does something with this file, the path should probably be updated as well in the build script.

### CODE REVIEW

File: core/pom.xml [hunk 1]
```diff
@@ -153,8 +143,12 @@
 			<artifactId>opennlp-tools</artifactId>
 		</dependency>
 		<dependency>
+			<!-- TODO: NemexWekaClassificationEDATest throws "java.lang.Exception: liblinear classes not in CLASSPATH!".
+            This requires a wrapper but the one in https://github.com/bwaldvogel/liblinear-weka is outdated. -->
 			<groupId>de.bwaldvogel</groupId>
 			<artifactId>liblinear</artifactId>
+			<version>2.11</version>
```
Comment (homosepian) [inline core/pom.xml]: @madhumita-git can you please verify that this is the correct version? In your commit it was set to 1.5 but versions start at 1.7.1 in Maven Central
Also, build succeeds and all tests pass but NemexWekaClassificationEDATest throws "java.lang.Exception: liblinear classes not in CLASSPATH". Does it happen in your environment as well?

Comment (reckart) [inline core/pom.xml]: If Weka or whatever dependency requires liblinear was built against the a v1.x version of liblinear, it will likely not work with 2.x. The 1.7.1 version on Maven Central is one that the maintainer did on special request by us because some older NLP tools make use of it. Better check which version you really need.

Comment (homosepian) [inline core/pom.xml]: @reckart when you say "by us", do you mean by DKPro? I just tried to build with 1.7.1 but it looks like it's incompatible with DKPro core 1.4.0:
```
java.lang.NoClassDefFoundError: Lde/bwaldvogel/liblinear/SolverType;
at java.lang.Class.getDeclaredFields0(Native Method)
...
at de.tudarmstadt.ukp.dkpro.core.maltparser.MaltParser.process(MaltParser.java:274)
...
```
Do you know which liblinear version is compatible with DKPro 1.4.0? And actually I'm trying to upgrade to DKPro 1.8.0, which I assume will work with the latest liblinear version, right?

If the problem with weka/liblinear is in the EOP code then it shouldn't be too difficult to refactor it to work with the latest version. So I'd rather try to keep the dkpro dependencies "happy" for now, so to speak.

Comment (reckart) [inline core/pom.xml]: Actually, different modules in DKPro Core use different versions of liblinear. It is not our choice - the underlying NLP tools require these different versions. liblinear 1.7.1 was created to be compatible with matetools. However, maltparser requires liblinear 1.8. Between 1.7.1 and 1.8, the names of the class package was changed from "liblinear" to "de.bwaldvogel.liblinear". matetools and maltparser cannot be easily combined in the same application.

Comment (homosepian) [inline core/pom.xml]: I see, tricky one! I could solve it with ClassLoaders, by loading one version of liblinear for the weka-based code and another for the rest of eop. But actually I see that the new version of weka is compatible with the new package structure of liblinear. The only problem is you also need a wrapper-jar, which is not available in a public maven repo (as far as I can find). You get it if you use the weka package-manager to install liblinear locally.
Maybe the least-ugly solution for now would be to provide the liblinear library + wrapper as part of the EOP installation.

File: alignmentedas/src/main/java/eu/excitementproject/eop/alignmentedas/p1eda/classifiers/EDABinaryClassifierFromWeka.java [hunk 2]
```diff
@@ -129,7 +127,7 @@ public DecisionLabelWithConfidence classifyInstance(
 		// Make a new instance, with the given feature vector. 
 		Instance anInstance = null; 
 		try {
-			anInstance = new Instance(featureVector.size()); 
+			anInstance = new BinarySparseInstance(featureVector.size());
```
Comment (homosepian) [inline alignmentedas/src/main/java/eu/excitementproject/eop/alignmentedas/p1eda/classifiers/EDABinaryClassifierFromWeka.java]: Not sure if this is the right concrete class to use. Options are DenseInstance, SparseInstance, BinarySparseInstance.

File: alignmentedas/src/main/java/eu/excitementproject/eop/alignmentedas/p1eda/classifiers/EDABinaryClassifierFromWeka.java [hunk 3]
```diff
@@ -433,7 +433,7 @@ private Instances buildTrainingDataSet(List<LabeledInstance> gold) throws ValueE
 			}
 			
 			// prepare an instance with feature values ... 
-			Instance anInstance = new Instance(featureSize + 1); 
+			Instance anInstance = new BinarySparseInstance(featureSize + 1);
```
Comment (homosepian) [inline alignmentedas/src/main/java/eu/excitementproject/eop/alignmentedas/p1eda/classifiers/EDABinaryClassifierFromWeka.java]: Available concrete classes: DenseInstance, SparseInstance, BinarySparseInstance.

File: core/src/main/java/eu/excitementproject/eop/core/metaeda/SimpleMetaEDAConfidenceFeatures.java [hunk 4]
```diff
@@ -215,7 +211,7 @@ public void startTraining(CommonConfig c) throws EDAException, LAPException {
 				goldAnswers.add(goldAnswer);
 				
 				//add new instance to dataset
-				Instance instance = new Instance(scores.size());
+				Instance instance = new DenseInstance(scores.size());
```
Comment (homosepian) [inline core/src/main/java/eu/excitementproject/eop/core/metaeda/SimpleMetaEDAConfidenceFeatures.java]: Available concrete classes: DenseInstance, SparseInstance, BinarySparseInstance.

File: core/src/main/java/eu/excitementproject/eop/core/metaeda/SimpleMetaEDAConfidenceFeatures.java [hunk 5]
```diff
@@ -316,7 +312,7 @@ public void startTraining(String language, boolean confidenceAsFeatures, boolean
 				goldAnswers.add(goldAnswer);
 	
 				//add new instance to dataset
-				Instance instance = new Instance(scores.size());
+				Instance instance = new DenseInstance(scores.size());
```
Comment (homosepian) [inline core/src/main/java/eu/excitementproject/eop/core/metaeda/SimpleMetaEDAConfidenceFeatures.java]: Available concrete classes: DenseInstance, SparseInstance, BinarySparseInstance.
